sudo: required
dist: trusty
language: node_js
node_js: 9.11.1
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - sudo apt-get update -qq
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm install -g web-component-tester@v6.0.0
  - npm install -g
  - npm install -g eslint-config-airbnb@14.1.0 eslint@3.19.0 eslint-plugin-jsx-a11y@4.0.0 eslint-plugin-import@2.2.0 eslint-plugin-react@6.10.3
script:
  - eslint src/
  - wct --module-resolution=node --npm --skip-plugin sauce --plugin local -l chrome

